//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Soccer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangXepHang
    {
        public int MaXepHang { get; set; }
        public Nullable<int> MaGiaiDau { get; set; }
        public Nullable<int> MaDoi { get; set; }
        public string MuaGiai { get; set; }
        public Nullable<int> ViTri { get; set; }
        public Nullable<int> SoTranDau { get; set; }
        public Nullable<int> SoTranThang { get; set; }
        public Nullable<int> SoTranHoa { get; set; }
        public Nullable<int> SoTranThua { get; set; }
        public Nullable<int> BanThang { get; set; }
        public Nullable<int> BanThua { get; set; }
        public Nullable<int> HieuSo { get; set; }
        public Nullable<int> Diem { get; set; }
    
        public virtual DoiBong DoiBong { get; set; }
        public virtual GiaiDau GiaiDau { get; set; }
    }
}
