//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Soccer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChuyenNhuong
    {
        public int MaChuyenNhuong { get; set; }
        public Nullable<int> MaCauThu { get; set; }
        public Nullable<int> MaDoiCu { get; set; }
        public Nullable<int> MaDoiMoi { get; set; }
        public Nullable<System.DateTime> NgayChuyenNhuong { get; set; }
        public Nullable<decimal> PhiChuyenNhuong { get; set; }
    
        public virtual CauThu CauThu { get; set; }
        public virtual DoiBong DoiBong { get; set; }
        public virtual DoiBong DoiBong1 { get; set; }
    }
}
