//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Soccer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QlyBongDaEntities : DbContext
    {
        public QlyBongDaEntities()
            : base("name=QlyBongDaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BangXepHang> BangXepHangs { get; set; }
        public virtual DbSet<CauThu> CauThus { get; set; }
        public virtual DbSet<ChanThuong> ChanThuongs { get; set; }
        public virtual DbSet<ChuyenNhuong> ChuyenNhuongs { get; set; }
        public virtual DbSet<DoiBong> DoiBongs { get; set; }
        public virtual DbSet<DoiHinhTranDau> DoiHinhTranDaus { get; set; }
        public virtual DbSet<GiaiDau> GiaiDaus { get; set; }
        public virtual DbSet<HuanLuyenVien> HuanLuyenViens { get; set; }
        public virtual DbSet<LichThiDau> LichThiDaus { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<SanVanDong> SanVanDongs { get; set; }
        public virtual DbSet<SuKienTranDau> SuKienTranDaus { get; set; }
        public virtual DbSet<ThongKeTranDau> ThongKeTranDaus { get; set; }
        public virtual DbSet<TranDau> TranDaus { get; set; }
        public virtual DbSet<TrongTai> TrongTais { get; set; }
    }
}
