//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Soccer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoiHinhTranDau
    {
        public int MaDoiHinh { get; set; }
        public Nullable<int> MaTran { get; set; }
        public Nullable<int> MaDoi { get; set; }
        public Nullable<int> MaCauThu { get; set; }
        public string ViTri { get; set; }
        public Nullable<bool> LaDoi11Chinh { get; set; }
        public Nullable<int> SoAo { get; set; }
    
        public virtual CauThu CauThu { get; set; }
        public virtual DoiBong DoiBong { get; set; }
        public virtual TranDau TranDau { get; set; }
    }
}
