//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Soccer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichThiDau
    {
        public int MaLich { get; set; }
        public Nullable<int> MaTran { get; set; }
        public Nullable<int> MaGiaiDau { get; set; }
        public Nullable<int> MaDoiNha { get; set; }
        public Nullable<int> MaDoiKhach { get; set; }
        public Nullable<int> MaSan { get; set; }
        public Nullable<System.DateTime> ThoiGianDuKien { get; set; }
        public string TrangThai { get; set; }
        public Nullable<int> TiSoDoiNha { get; set; }
        public Nullable<int> TiSoDoiKhach { get; set; }
    
        public virtual DoiBong DoiBong { get; set; }
        public virtual DoiBong DoiBong1 { get; set; }
        public virtual GiaiDau GiaiDau { get; set; }
        public virtual SanVanDong SanVanDong { get; set; }
        public virtual TranDau TranDau { get; set; }
    }
}
