//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Soccer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuKienTranDau
    {
        public int MaSuKien { get; set; }
        public Nullable<int> MaTran { get; set; }
        public Nullable<int> MaDoi { get; set; }
        public Nullable<int> MaCauThu { get; set; }
        public Nullable<int> MaCauThuGhiBan { get; set; }
        public string LoaiSuKien { get; set; }
        public Nullable<int> PhutThoiGian { get; set; }
        public Nullable<int> PhutBuGio { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> MaCauThuKienTao { get; set; }
    
        public virtual CauThu CauThu { get; set; }
        public virtual CauThu CauThu1 { get; set; }
        public virtual CauThu CauThu2 { get; set; }
        public virtual DoiBong DoiBong { get; set; }
        public virtual TranDau TranDau { get; set; }
    }
}
