//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Soccer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongKeTranDau
    {
        public int MaThongKe { get; set; }
        public Nullable<int> MaTran { get; set; }
        public Nullable<int> MaDoi { get; set; }
        public Nullable<int> MaCauThu { get; set; }
        public Nullable<int> TiLePhoiHop { get; set; }
        public Nullable<int> SoLanSut { get; set; }
        public Nullable<int> SoLanSutTrungDich { get; set; }
        public Nullable<int> SoPhatGoc { get; set; }
        public Nullable<int> SoLanPhamLoi { get; set; }
        public Nullable<int> SoTheVang { get; set; }
        public Nullable<int> SoTheDo { get; set; }
        public Nullable<int> SoLanVietVi { get; set; }
    
        public virtual CauThu CauThu { get; set; }
        public virtual DoiBong DoiBong { get; set; }
        public virtual TranDau TranDau { get; set; }
    }
}
