//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Soccer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TranDau
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TranDau()
        {
            this.DoiHinhTranDaus = new HashSet<DoiHinhTranDau>();
            this.LichThiDaus = new HashSet<LichThiDau>();
            this.SuKienTranDaus = new HashSet<SuKienTranDau>();
            this.ThongKeTranDaus = new HashSet<ThongKeTranDau>();
        }
    
        public int MaTran { get; set; }
        public Nullable<int> MaGiaiDau { get; set; }
        public Nullable<int> MaDoiNha { get; set; }
        public Nullable<int> MaDoiKhach { get; set; }
        public Nullable<int> MaSan { get; set; }
        public Nullable<System.DateTime> ThoiGianDuKien { get; set; }
        public string TrangThai { get; set; }
        public Nullable<int> MaTrongTaiChinh { get; set; }
        public Nullable<int> TiSoDoiNha { get; set; }
        public Nullable<int> TiSoDoiKhach { get; set; }
    
        public virtual DoiBong DoiBong { get; set; }
        public virtual DoiBong DoiBong1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoiHinhTranDau> DoiHinhTranDaus { get; set; }
        public virtual GiaiDau GiaiDau { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichThiDau> LichThiDaus { get; set; }
        public virtual SanVanDong SanVanDong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuKienTranDau> SuKienTranDaus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongKeTranDau> ThongKeTranDaus { get; set; }
        public virtual TrongTai TrongTai { get; set; }
    }
}
